let actionTypes = {
    ADJUST_WAVEFORM: 'ADJUST_WAVEFORM',
    ADJUST_VOLUME: 'ADJUST_VOLUME',
    ADJUST_FREQUENCY: 'ADJUST_FREQUENCY',
    ENABLE_VIBRATO: 'ENABLE_VIBRATO',
    DISABLE_VIBRATO: 'DISABLE_VIBRATO',
    MOVE_VIBRATO: 'MOVE_VIBRATO'
};

export default actionTypes;